main:
  - name: Syllabus
    url: https://github.com/lbelzile/experimental/raw/main/static/syllabus/MATH80667A_F21_Syllabus.pdf
    weight: 1
  - name: Notes
    url: https://lbelzile.github.io/math80667a/
    weight: 12 
  - name: Content
    url: /content/
    weight: 3
  - name: Examples
    url: /example/
    weight: 4
  - name: Evaluations
    url: /evaluations/
    weight: 5


content:
  - name: Overview
    weight: 1
  - name: Course content
    weight: 2
example:
  - name: Overview
    weight: 1
  - name: Simulated data
    weight: 2
  - name: Examples
    weight: 3
evaluations:
  - name: Evaluations
    weight: 1
  - name: Weekly check-in
    weight: 2
  - name: Problem sets
    weight: 3
  - name: Final project
    weight: 4
  - name: Final exam
    weight: 5

