main:
  - name: Syllabus
    url: https://github.com/lbelzile/experimental/raw/main/static/syllabus/MATH80667A_F21_Syllabus.pdf
    weight: 1
  - name: Content
    url: /content/
    weight: 2
  - name: Examples
    url: /example/
    weight: 3
  - name: Assignments
    url: /assignment/
    weight: 4
  - name: Resources
    url: "https://evalf21.classes.andrewheiss.com/resource/"
    weight: 5

content:
  - name: Overview
    weight: 1
  - name: Course content
    weight: 2
example:
  - name: Overview
    weight: 1
  - name: Simulated data
    weight: 2
  - name: Examples
    weight: 3
assignment:
  - name: Assignments
    weight: 1
  - name: Weekly check-in
    weight: 2
  - name: Problem sets
    weight: 3
  - name: Final exam
    weight: 4

